stack/CO_SDO.h
because it took me some hours fo find out :-)
=> Add usage example for SDO access by ID

stack/CO_NMT_Heartbeat.c, stack/CO_NMT_Heartbeat.h
Followup to question on sourceforge [https://sourceforge.net/p/canopennode/discussion/387151/thread/a760f632/](https://sourceforge.net/p/canopennode/discussion/387151/thread/a760f632/)
=> Added callback and query function for NMT state

stack/CO_SDO.c, stack/CO_SDO.h
For details see https://sourceforge.net/p/canopennode/discussion/387151/thread/a9d12d35/
Please have a close look if I made a mistake.
=> OD 1003-0 now clears errors

stack/CO_trace.c
Fix warning from -Wsign-compare.
=> Fix signed/unsigned comparisons

CANopen.c, CANopen.h, stack/CO_Emergency.c, stack/CO_LSSmaster.c, stack/CO_NMT_Heartbeat.c, stack/CO_PDO.c, stack/CO_SDO.c, stack/CO_TIME.c, stack/drvTemplate/CO_driver.c
Including:
Shadowing
Missing default cases
Missing cases in switch statements
unused variables
Pointer problems
Function declarations' visibility
Large integer implicitly truncated to unsigned type
Statement may fall through
Most work was done by Michele B.
https://github.com/blankm/CANopenNode.git
=> Warnings omitted

CANopen.c
=> Fix RX Buffer size

CANopen.c, CANopen.h, stack/CO_PDO.c, stack/CO_PDO.h, stack/CO_SYNC.c, stack/CO_SYNC.h
=> Implementing PDO and SYNC timerNext_us return value

stack/CO_trace.c
This extends #144, commit f2283e3ca98650b321ae51a2d4e69e21dd45aa32
=> CO_trace: fix warning "cast increases required alignment of target type"

stack/CO_LSSslave.c
Fix the buffer overflow in the service inquire
=> LSS slave: fix a buffer overflow

stack/CO_SDO.c
This is critical fix for PR #174 (issue #39)
In 5967fc607c502bb52009e8ecaa7c565f5f55f908 I missed checking isNew also in `if(!NMTisPreOrOperational){}`. Without this process pointer could overrun receive pointer on receiving NMT stop command during active SDO communication - this totally breaks all further proper working.
Now checking, if buffer is empty before freeing it, is always done inside CO_SDO_process_done for sure.
=> SDO: fix to always check if buffer is empty before freeing it

301/CO_TIME.h, example/CO_OD.h
Fix for V2: Time has a direct dependency to OD.
See #226
=> move timeOfDay_t union to CO_TIME.h

301/CO_ODinterface.c, 301/CO_SDOserver.c, 301/CO_TIME.c, 301/CO_fifo.c, CANopen.c, example/main_blank.c, socketCAN/CO_driver.c, socketCAN/CO_error.c
Fix #275 
I separated the different type of fix then you can choose if you do not want to apply something.
I could not run clang-format as this change a lot of files according to `ColumnLimit:` maybe you want to adjust this value on `.clang-format` ?
=> Warning fixes

301/CO_SDOclient.c
=> remove VLA from SDOclient in newOD branch

CANopen.c
Replaced `calloc/free` with `CO_alloc` and `CO_free` respectively.
Added macro to allocate memory for all modules, makes code more clean.
=> Replace malloc/free with CO_ and add macro for complete allocation

301/CO_SDOclient.c
=> fixed typo in sdo client

301/CO_PDO.c
Added inhibitTime and eventTime casting to uint32_t
=> TPDO inhibitTime_us / evnetTime_us calculation fix

304/CO_SRDO.c, CANopen.c
These are the second changes to make SRDO work correctly in Rx direction
=> Fix srdo second part

304/CO_SRDO.c, CANopen.c
These are the first changes to make SRDO work correctly in Tx direction
=> Fix srdo first part

example/CO_driver_blank.c
This is a small fix on a variable name
=> Fixed txErrors variable name

301/CO_ODinterface.c
The removed `break;` statement is unreachable and currently generates an error when compiled with ARM compiler (warning 111-D).
=> Remove unreachable statement in CO_ODinterface.c

305/CO_LSSmaster.c
Added CO_SWAP_** macros to fix LSS master endianness
=> Fixed LSS master message byteswapping for big endian system
