- CANopen.c
- CANopen.h
- stack/CO_SDO.c
- stack/CO_SDO.h
These are the changes I mentioned for multiple SDO servers. (At least as I understand how it should work)
Unless I'm mistaken the first server must be the default one (COB 0x580/0x600 + node id) but the others can be whatever you want
I also added a parameter "offset" to ODF_arg_t to allow multiple simultaneous reads of the same Domain OD object, this parameter should replace the static variable you had in ODF callback function. The ODF callback still has to take care of multiple simultaneous writes though, that might cause headache...
Best regards
Jens
> Allow multiple SDO objects

- stack/STM32F3/CO_Flash.c
- stack/STM32F3/CO_Flash.h
- stack/STM32F3/CO_driver.c
- stack/STM32F3/CO_driver.h
Pull request includes initial CAN and Flash drivers for STM32F3-family of microcontrollers. CAN driver is based on the existing STM32F1 driver in the reposirory and the Flash-driver is based on the Atmel SAM3X Flash driver. 
A custom-made STM32F334-based board was used in the development and things seem to work in basic desktop testing with simple CANOpen bus of two devices. No testing in real CANOpen environment is done yet. Any feedback or improvement ideas are welcome!
> Driver for STM32F3xx-microcontrollers

- stack/LPC1768/CO_CAN.h
- stack/LPC1768/CO_driver.cpp
- stack/LPC1768/CO_driver.h
This adds LPC1768 driver for CANopenNode.
This is implemented using mbed SDK. This is currently tested on a mbed LPC1768 board and will be tested on a custom-made board with a LPC1768.
CAN Rx filters are not yet implemented on the mbed SDK for LPC1768 target and therefore not implemented in this driver.
Feel free to comment
Best regards
Ben
> Add LPC1768 driver

- CANopen.c
Assuming a valid node ID in the middle of the range is a very bad idea for production environment. Changed so it returns an error.
A different approach would be to use something like ID 127.
> CO_init assumes node ID 16 if invalid

- CANopen.c
- stack/crc16-ccitt.c
- stack/crc16-ccitt.h
This enables the stack user to use a different calculation method. This
is needed to save space (no table) or to use hardware crc unit.
Implementation can be located in driver directory.
> Compiler switch enables providing own CRC16 implemetation.

- CANopen.h
- stack/CO_Emergency.h
- stack/CO_HBconsumer.h
- stack/CO_NMT_Heartbeat.h
- stack/CO_PDO.h
- stack/CO_SDO.h
- stack/CO_SDOmaster.h
- stack/CO_SYNC.h
- stack/CO_trace.h
- stack/crc16-ccitt.h
- stack/drvTemplate/CO_driver.h
- stack/drvTemplate/eeprom.h
This only has an effect if cpp compiler is used. C compiler doesn't have the "__cplusplus" macro set.
> Added guards for c++ compilation

- stack/CO_PDO.c
Entry for dummy mapping cannot be found because there is no OD entry for that.
> PDO dummy mapping caused invalid memory access

- stack/CO_trace.c
snprintf() calls will raise warnings when using %u/%d
format strings with uint32_t/int32_t arguments.
Use %lu/%ld instead.
> CO_trace: remove compiler warnings

- stack/CO_Emergency.c
This ensures that an queue overflow error is only active as long as the queue is actually overflown. Currently, this error remains active until reset and cannot be cleared.
> emergency processing generates emcy queue overflow cleared message

- stack/CO_Emergency.c
This is better than the current solution, however if a user wants to implement a device profile, change to the source is still necessary to set device profile error bit.
> manufacturer bit in error register didn't work

- CANopen.c
- stack/CO_Emergency.c
- stack/CO_Emergency.h
A feature which I've found lacking was the inability to take action when another node on the network transmits an emergency message.  These commits expand the emergency message callback to function similarly to the NMT callback.  Instead of this callback being called only on transmission of an emergency message it is now called on reception of one as well.
For example, we wanted our master (in this case canopend) to report any emergency messages on the bus by passing them through the command socket.  
First we define a handler:
```
/* Handle CANopen emergency messages. */
void EM_report(const uint16_t ident,
const uint16_t errorCode,
const uint8_t errorRegister,
const uint8_t errorBit,
const uint32_t infoCode) {
char buf[40];
int len;
len = sprintf(buf,
"EM: %04x %04x %02x %02x %08x\r\n", …
```
> Emergency Message RX Callback

- stack/CO_trace.c
This fixes commit 533801574055c5dacf60fb6b18930c288336dce1 on 32-bit ARM with GCC 8.3.0 (among others).
> Use inttypes.h for 32 bit signed/unsigned format specifiers.

- CANopen.c
#if CO_NO_SDO_CLIENT == 1
should be  
#if CO_NO_SDO_CLIENT != 0
if the loop should make sense 
#if CO_NO_SDO_CLIENT != 0
for(i=0; i<CO_NO_SDO_CLIENT; i++) {
free(CO->SDOclient[i]);
}
> Correct handling if there is more than one SDO client configured

- stack/drvTemplate/CO_driver.h
- stack/neuberger-socketCAN/CO_driver_base.h
- stack/socketCAN/CO_driver.h
Cast the pointer to `uintptr_t` instead of `int` in the implementations
of `IS_CANrxNew`.
> Sync: fix cast to integer of different size

- CANopen.c
- CANopen.h
- example/main.c
- stack/LPC1768/CO_driver.cpp
- stack/LPC1768/CO_driver.h
- stack/LPC177x_8x/CO_driver.c
- stack/LPC177x_8x/CO_driver.h
- stack/MCF5282/CO_driver.c
- stack/MCF5282/CO_driver.h
- stack/PIC24_dsPIC33/CO_driver.c
- stack/PIC24_dsPIC33/CO_driver.h
- stack/PIC32/CO_driver.c
- stack/PIC32/CO_driver.h
- stack/SAM3X/CO_driver.c
- stack/SAM3X/CO_driver.h
- stack/STM32/CO_driver.c
- stack/STM32/CO_driver.h
- stack/STM32F3/CO_driver.c
- stack/STM32F3/CO_driver.h
- stack/drvTemplate/CO_driver.c
- stack/drvTemplate/CO_driver.h
- stack/dsPIC30F/CO_driver.c
- stack/dsPIC30F/CO_driver.h
- stack/eCos/CO_driver.c
- stack/eCos/CO_driver.h
- stack/neuberger-socketCAN/CO_driver.c
- stack/neuberger-socketCAN/CO_driver.h
- stack/neuberger-socketCAN/CO_driver_base.h
- stack/socketCAN/CO_driver.c
- stack/socketCAN/CO_driver.h
Previously, the address of the CAN device (`CANbaseAddress`)
was specified as a signed or unsigned integer of variable size.
This made the ABI specific for each driver and is not generic
enough for some use cases.
Replaced all usages by a void pointer. Renamed `CANbaseAddress`
to `CANdevicePtr`.
Refactored the code where it needed to be (some comparisons to -1).
> Use a void pointer for the CAN device address

- stack/CO_Emergency.c
This fixes direct use of `msg->ident` to instead use the `CO_CANrxMsg_readIdent()` abstraction function, since not all drivers employ the same `CO_CANrxMsg_t` structure as it is a system-specific struct.
> Fixed direct use of msg->ident to use driver abstraction function

- CANopen.c
Fix missing free for TIME as pointed out by @blankm in #110
> fix: CO_delete free TIME

- stack/CO_LSSslave.c
- stack/CO_PDO.c
- stack/CO_SDO.c
- stack/neuberger-socketCAN/CO_Linux_threads.c
- stack/neuberger-socketCAN/CO_driver.c
- stack/neuberger-socketCAN/CO_error.c
Removed comparisons of boolean values to `false` and `true`. Evaluating
them is enough.
> Fix bool equality checks

- CO_driver.h
- CO_types.h
- stack/LPC1768/CO_driver_target.h
- stack/LPC177x_8x/CO_driver_target.h
- stack/MCF5282/CO_driver_target.h
- stack/PIC24_dsPIC33/CO_driver_target.h
- stack/PIC32/CO_driver_target.h
- stack/SAM3X/CO_driver_target.h
- stack/STM32/CO_driver_target.h
- stack/STM32F3/CO_driver_target.h
- stack/drvTemplate/CO_driver_target.h
- stack/dsPIC30F/CO_driver_target.h
- stack/eCos/CO_driver_target.h
- stack/neuberger-socketCAN/CO_driver.c
- stack/neuberger-socketCAN/CO_driver_target.h
- stack/socketCAN/CO_driver_target.h
Created a single header file (`CO_driver.h`) to declare the functions
of the drivers API. This forces drivers to use a common API.
Previously, each driver declared these functions in its specific
`CO_driver.h` file. This causes two issues:
1. while these functions are used in target-independent code,
the declarations could be target specific, leading to API/ABI
compatibility issues.
2. the declarations were duplicated for each driver.
The `CO_driver.h` files for each driver were renamed to
`CO_driver_target.h`. This file is included from `CO_driver.h`.
Added a new header for types: `CO_types.h`. This file currently
holds the definition of `CO_ReturnError_t` that was previously
duplicated for all drivers. Added a few enum values to support
the `neuberger-socketCAN` code.
> Single project-wide header for driver functions

- CANopen.c
- CANopen.h
- example/main.c
- stack/CO_PDO.c
- stack/CO_PDO.h
- stack/PIC32/main_PIC32.c
- stack/neuberger-socketCAN/CO_Linux_threads.c
- stack/socketCAN/CO_Linux_tasks.c
This change will allow CO_NO_SYNC to be zero if the project does not wish to use the sync message.
If CO_NO_SYNC is zero the stack does not need to assign a mailbox to it, which is important if you are using hardware filtering and only have a limited number of mailboxes to work with.  This also means you do not have to define EDS entries 1005-1007.
Changes:
- feature verification no longer asserts on `CO_NO_SYNC == 0`
- `CO_SYNC_t COO_SYNC` is no longer allocated if `CO_NO_SYNC == 0`
- `CO_SYNC_init` will not be called if `CO_NO_SYNC == 0`
- split `CO_process_SYNC_RPDO` into two separate functions.
- `bool_t CO_process_SYNC`  (returns syncWas)
- `void CO_process_RPDO` (takes syncWas)
- SYNC is now passed to TPDO on init rather than at every process call.
- Both TPDO and RPDO will now …
> change SYNC module to be optional

- stack/CO_trace.c
- stack/CO_trace.h
Fix compile error by guarding CO_trace with `#if CO_NO_TRACE > 0` as suggested by @wilkinsw #118
> guard CO_trace to be optionnal

- CANopen.c
#128 forgot to guard CO_memoryUsed and errCnt.
This would result in CO_ERROR_OUT_OF_MEMORY being returned erroneously if CO_USE_GLOBALS and CO_NO_SYNC were both 0.
> fix missing SYNC guards

- CANopen.c
Add guards to TIME module similar to #128 
Makes defining EDS entries 0x1012 and 0x1013 optional.
@JuPrgn I'd appreciate if you could take a look at this since I do not use TIME for my application.
> change TIME module to be optional

- CANopen.c
- stack/CO_NMT_Heartbeat.c
OD_NMTStartup (0x1F80 OD) can be optional
issue #149
> fix NMTstartup handling if device is NOT the NMT Master

- CANopen.c
This simply removes the maximum 50ms time restriction on timerNext_ms to allow interrupt driven tickless RTOS to schedule the next event and sleep for extended periods.
> Removed maximum time restriction on timerNext_ms

- stack/CO_SDO.c
- stack/CO_SDO.h
Now additional state CO_SDO_ST_DOWNLOAD_BL_SUB_RESP_2 is used to send response without resetting SDO sequence.
Refactoring timeout halding logic in sub-block transfer.
Also add missed unsigned indicators for several constants.
issue #170
> fix SDO block download process continuity after sequence breaks

- 301/CO_PDO.c
- 301/CO_PDO.h
- 301/CO_SYNC.c
- 301/CO_SYNC.h
- 301/CO_config.h
- example/CO_driver_target.h
- socketCAN/CO_driver_target.h
Add CO_RPDO_initCallbackPre() and CO_SYNC_initCallbackPre(), which are functionally identical to functions for SDO, NMT, HB and so on. With the addition of these two new functions, a callback invoked after reception of SYNC or RPDO can immediately wake the thread that processes these messages. Moreover - it is now much easier to handle CANopenNode in _one_ thread (instead of two - one for CO_process() and another one for periodic processing of SYNC, RPDO and TPDO). With these callbacks everything can be easily and efficiently handled in a single thread. Such change will drastically reduce RAM consumption (1 thread instead of 2) and also OS overhead (less context switches), at zero cost - due to callbacks the default value of timerNext_us can be extremely big (say UINT32_MAX), but the …
> Add CO_..._initCallbackPre() for RPDO and SYNC

- 301/CO_SDOserver.c
Function did not check whether the object had any flags assigned. It
makes no difference for objects with no subindexes, because then the
function will return NULL anyway. But is subIndex argument is not zero,
then the function calculates addresses of flags as offsets from NULL.
For example, for an object with no flags assigned, when subIndex == 5,
the function would return 5 as the address instead of the expected NULL.
> Fix pointer bug in CO_OD_getFlagsPointer()

- 301/CO_SYNC.c
- 301/CO_SYNC.h
- CANopen.c
Replace hard-coded values with enums and explicit manage all enumeration
values in CO_process_SYNC() to avoid warnings like this:
CANopen.c:837:5: warning: enumeration value ‘CO_SYNC_NONE’ not handled in switch [-Wswitch]
837 |     switch (sync_process) {
|     ^~~~~~
> CO_SYNC_process: use enums instead of uint8_t

- 301/CO_SDOclient.h
- 301/CO_config.h
Include `CO_fifo.h` in `CO_SDOclient.h` in all cases
Struct `CO_SDOclient_t` has `CO_fifo_t` member no matter what configuration
is set, so the header is always required. Without this change the build
fails when `CO_CONFIG_SDO_CLI_SEGMENTED` is not enabled.
> Fix fifo include

- 301/CO_SDOserver.c
- 305/CO_LSSmaster.c
Mainly replace array elements copy with `memcpy()` and buffer reset with `memset()`
> Use memcpy() and memset() where possible

- 301/CO_TIME.c
Use standard idiom for integer rounding up.
Signed-off-by: Paolo Teti <paolo.teti@gmail.com>
> TIME: fix round up conversion from usec to msec

- 301/CO_SDOserver.c
GCC 10 static analyzer (`-fanalyzer`) warn about possible dereference of NULL ‘ext’ on 'ext->pODFunc'.
This patch adds a guard on 'ext' to fix the issue.
> GCC 10: Fix dereference of NULL warning

- 301/CO_SDOserver.h
- 301/CO_config.h
- 301/CO_driver.h
- 304/CO_GFC.c
- 304/CO_GFC.h
- 304/CO_SRDO.c
- 304/CO_SRDO.h
- CANopen.c
- CANopen.h
- Makefile
- example/CO_OD.h
- example/CO_driver_target.h
- example/Makefile
This pull request implements the CANopen Safety protocol.
The main code is in the directory `/304` (This is the old name of the spec but I think it is better suited). I used parts of the PDO code as template.
The open points without questionmark are on my TODO list. For the points with question marks the implementation is unclear.
[mapping array subindex 0](https://github.com/CANopenNode/CANopenNode/issues/162#issuecomment-643961924)
Currently I can only test manually, by checking the CAN bus , so expect some bug. I encouraged everyone to try the code and give feedback, especially when you can test it in combination with existing CANopen Safety devices.
This code is not certified/verified. So if you want to use it in SIL applications you have to do it yourself. It applies, as already …
> CANopen Safety (SRDO according to DIN EN 50325-5:2016)

- stack/CO_LSSmaster.c
Fix a buffer overflow in the switch mode selective
> LSS master: fix a buffer overflow

- stack/CO_SDO.c
Fix wrong double calling CO_SDO_receive_done for last segment in subblock/block.
This is critical fix for PR #174
issue #39
Before this patch SDO block download was not working if there is no sequence breaks or timeouts (if SDO buffer not gets empty while receiving block). If data size is bigger or equal to blocksize, on receiving last segment, bug caused SDO to process wrong message buffer from FIFO while waiting block end sequence that leads to SDO abort 0504 0001h (client/server command specifier not valid or unknown).
It was caused by wrong double calling CO_SDO_receive_done on block end (one call in full buffer check and one in block end check) that broke FIFO receive pointer. Workaround was to set CO_SDO_BUFFER_SIZE greater than 127*7 (889 bytes) or work with CANopen master that …
> SDO: fix broken block download

- 309/CO_gateway_ascii.c
This basically allows an application employing the 309 ASCII Gateway to define the default line termination (newline) sequence for things like help text and other returned strings.
As it was before, the line terminations were simply "\n". This works great for a Linux system, but doesn't work very well for serial connected MCUs that expect a "\r\n" sequence. By providing this configuration option in the driver target header file, the user can control the line termination sequence as appropriate for their needs.
> Defined ASCII Gateway Line Termination (Newline) configuration option

- 301/CO_SDOclient.c
- 301/CO_SDOserver.h
This is a subtle change to the CO_SDO_state_t enumeration that allows the upper nibble of the byte to be parsed as flags indicating whether the state is for an upload or download, and if it is a block transfer or not.
The idea behind this change is that a generic SDO client thread can wake up via the CO_SDOclient_initCallbackPre() defined callback function and check the SDO_C->state value to determine whether an upload or download is in progress (and optionally if it is a block type transfer). This allows the appropriate processing functions to be called without needing to track the state externally. Basically the thread just does a bitwise AND with SDO_C->state to determine if it needs to call CO_SDOclientDownload or CO_SDOclientUpload.
> Differentiate between SDO_C states by use of flags

- 305/CO_LSSslave.c
- 305/CO_LSSslave.h
- CANopen.c
This just disturbs my OCD.
It is inefficient, generates more code on smaller processors.
Some very old compilers for 8-bit controllers might not support this.
> lssAddress parameter by value

- 301/CO_SYNC.c
When SYNC timeout signals an error, this error are never reset, even though the next sync are on time.
To do this check in Preoperational, prevents the error to be stuck if Error behavior takes the node in preoperational on communication errors.
> Do ErrorReset when SYNC timeout are OK again.

- 301/CO_PDO.c
- 301/CO_PDO.h
- 301/CO_SYNC.c
- 301/CO_SYNC.h
This change adds the function CO_SYNCsend to allow for easier manual control of SYNC message generation. For example generating the SYNC message based on an external timer rather than from the process loop.
I also changed the return type of CO_TPDOsend() to CO_ReturnError_t to match CO_CANsend().
> Add CO_SYNCsend()

- 301/CO_HBconsumer.c
When current node is CO_HBconsumer_UNCONFIGURED then other nodes are skipped. You can increment pointer to node or break the cycle.
> CO_HBconsumer_process - skipped monitored nodes, useless cycles

- doc/deviceSupport.md
Update documentation with further details on the Zephyr RTOS support for CANopenNode.
> Update documentation with further details on the Zephyr RTOS support

- stack/CO_NMT_Heartbeat.c
- stack/CO_NMT_Heartbeat.h
When master, it's up to the application to put master state into operational.
We had a function to do this so that we don't have to write directly in NMT structure
> MNT: Add a function to set internal state

- CANopen.h
This adds a missing TIME object check to the CO_t struct. Without this, compilation fails with the following error message if no TIME object is enabled: ```CANopenNode/CANopen.h:271:5: error: unknown type name 'CO_TIME_t'```
> Added missing check for CO_NO_TIME definition to CANopen.h

- CANopen.c
I missed these on my last PR, my apologies. It looks like if the object was not included it used to set the pointer to NULL instead of just not including the object. This should fix that.
> Added additional missing time object checks

- CANopen.c
When using global CO objects, the heapMemoryUsed parameter of `CO_new(uint32_t *heapMemoryUsed)` is unused and generates a warning. This simply `(void)`'s it to suppress the warning.
> Suppressed unused heapMemoryUsed warning when using CO_USE_GLOBAL

- 301/CO_HBconsumer.c
- 301/CO_HBconsumer.h
- 301/CO_config.h
- example/CO_driver_target.h
- socketCAN/CO_driver_target.h
- socketCAN/CO_main_basic.c
* This way "remote NMT changed" callback is much more similar to other "multi" callbacks of HB consumer, and it was node-specific anyway, as you have to first configure the monitoring node to have that callback executed.
* Merge CO_CONFIG_HB_CONS_CALLBACK_CHANGE with ..._HB_CONS_CALLBACK_MULTI
These settings are now very similar, so there's no need to have two separate config options.
* Implement a better solution for #229
Instead of playing with incrementing pointers in various places it is better to just set it once at the start of loop.
These changes break the API.
> Make "remote NMT changed" callback of HB consumer node-specific

- 301/CO_HBconsumer.c
- 301/CO_HBconsumer.h
- 301/CO_config.h
- 305/CO_LSSslave.c
- socketCAN/CO_driver_target.h
- socketCAN/CO_error_msgs.h
- socketCAN/CO_main_basic.c
The user may decide whether he/she wants one common callback for all
monitored nodes (CO_CONFIG_HB_CONS_CALLBACK_CHANGE) or maybe separate
callbacks configured individually for each monitored mode
(CO_CONFIG_HB_CONS_CALLBACK_MULTI). These options cannot be set
simultaneously.
This change is related to the discussion in #237
Also fix a warning about shadowed local variables in CO_LSSslave.c
> Restore CO_CONFIG_HB_CONS_CALLBACK_CHANGE option

- doc/index.html
I ran a quick test with compiling on Windows WSL using a Yocto genereted SDK.
So far its working well, only problem I found is that the doc/index.html file is symlinked.
This is not supported on Windows, hence the repo gets flagged *dirty*.
I've checked on my linux system and the link is broken anyway so I guess it is not a problem to just remove that file?
> removed symlink to doc.html, not supported on Windows

- 305/CO_LSS.h
The default CO_CONFIG_LSS value has a syntax error in it.
> Fix default CO_CONFIG_LSS value

- 301/CO_NMT_Heartbeat.c
- 301/CO_NMT_Heartbeat.h
Noticed that when we set the nmt internal state directly that the attached callbacks are not triggered.
Easiest way to fix is as I did: trigger the callback from the setter function.
Let me know if the solution is not satisfying.
> BUGFIX: updating nmt internal state doesn't trigger callback function

- 301/CO_Emergency.c
- 301/CO_SDOserver.c
- 301/CO_TIME.h
Some structure members are only present when explicitly enabled by options.
Consequently, these members can only be used when the corresponding option is enabled.
I found some instances where this check in the code was missing and thus resulted in compile errors
> Fix build in NewOD for certain combinations of options

- 301/CO_HBconsumer.c
HB Consumer sub index 0 is `Highest sub-index supported` and should not be counted on number of HB consumers.
Without this, `CO_CANopenInit()` fails with error code -12 : `CO_ERROR_OD_PARAMETERS`
> Fix HBcons entries count

- 301/CO_Emergency.c
- 301/CO_NMT_Heartbeat.h
- 301/CO_SDOclient.c
- 301/CO_SDOserver.c
- 301/CO_fifo.h
- 305/CO_LSSmaster.c
- 305/CO_LSSmaster.h
- 305/CO_LSSslave.c
- 305/CO_LSSslave.h
- 309/CO_gateway_ascii.c
Hello, I fixed some warnings, that occured on my setup. A good bunch are just just typecasts, mostly because 
`sizeof(OD_size_t) != sizeof(size_t)` on 64 bit. I added the casts also in 301/CO_SDOclient.c but I am not sure if it is better to switch the function signatures instead (would also be consistent with the server part). 
bugs:
* 301/CO_SDOclient.c L 415 set invalid after return (noreachable code)
* 301/CO_SDOserver.c L 342 could lead to NULL access
* 301/CO_NMT_Heartbeat.hL 318 does not compile without cast when included in cpp file
> fixed some warnings & potential bugs

- 301/CO_PDO.c
The `CANrxData` field of the `CO_RPDO_t` struct is an array of `uint8_t` buffer with two elements if the node is SYNC-enabled; when copying the content of an RPDO to the object dictionary `CANrxData` is mistakenly indexed with an extra `[0]`, which ends up pointing to either the first or the second byte of the first buffer, resulting in erroneous RPDO transfers.
> Fixed bug with CANrxData buffer indexing

- 301/CO_PDO.c
Otherwise it may trigger error (if timer is not enabled)
> Add conditional compile statement for unused vars

- doc/deviceSupport.md
Adding support for Analog Devices MAX32662 and MAX32690 microcontrollers.
Update deviceSupport.md as per instructions listed for contributors. We will eventually want to include CANopenADI under CANopenNode project.
> Add Analog Devices MAX32xxx support

- 301/CO_PDO.c
- 301/CO_SDOserver.c
1. Variable name update in CO_PDO.c file
2. Correct use of pointer in the CO_SDOserver.c file
> Fix variable name and use of pointer for big endian system

- example/CO_driver_blank.c
TLDR:
Shifting ```noOfBytes``` by 12 is wrong, as it can overlap RTR bit, so all TX packets with 8 bytes payload will be RTR packets.
Details:
I developed my custom driver based on CO_driver_blank. I didn't care about how exactly CAN-ID, DLC and RTR bits are packed in the ```buffer.ident```, I just unpacked them later to send to the low-level driver, and figured out the packing was wrong.
I know it is just an example driver, but this small fix will probably save some time to someone else :)
> Fix bit shifting in CO_driver_blank/CO_CANtxBufferInit 

- 304/CO_SRDO.c
Only if the configuration is valid, the private variable is activated
(otherwise CO_SRDO_process will generate errors)
> Only if the configuration is valid, the private variable is activated

- 301/CO_SDOclient.c
- 301/CO_SDOserver.c
The variable is defined and assigned within the critical section, which prevents the critical section execution like:
```c
#define CO_LOCK_OD(...) do { /* Disable interrupts here */
#define CO_UNLOCK_OD(...) }while(0)
```
Such code generates its own local block and:
- Throws out compilation error if for whatever reason user wrongly calls lock/unlock or calls them too many times
- allows the use of local variable for interrupts state before interrupts are disabled.
Please check this issue: https://github.com/CANopenNode/CanOpenSTM32/issues/34#issuecomment-2948859635
> Define the ODR return variable before it is assigned for critical access
